config/routes.rb
Rails.application.routes.draw do
  root 'contacts#index'

  scope '(:locale)' do
    resources :contacts
    resources :phones, only: [:edit, :update, :destroy]
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :contact

  validates :address1, :city, :state, :country, :zip_code, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_one :address, dependent: :destroy
  has_many :phones, dependent: :destroy

  validates :name, :last_name, presence: true

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phones

  translates :bio

  def to_s
    "#{name} #{last_name}"
  end
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact

  validates :number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:destroy, :show, :update, :edit]

  def index
    @q = Contact.ransack(params[:q])
    @contacts = @q.result(distinct: true)
  end

  def new
    @contact = Contact.new
    @contact.build_address
    @contact.phones.build
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to @contact
    else
      render :new
    end
  end

  def update
    if @contact.update_attributes(contact_params)
      redirect_to @contact
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_url
  end

  private
  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :last_name, :bio, address_attributes: [
      :address1, :address2, :city, :state, :country, :zip_code
    ], phones_attributes: [:number])
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:edit, :update, :destroy]

  def edit; end

  def update
    if @phone.update_attributes(phone_params)
      redirect_to @phone.contact
    else
      render :edit
    end
  end

  def destroy
    contact = @phone.contact
    @phone.destroy
    redirect_to contact
  end

  private

  def set_phone
    @phone = Phone.find(params[:id])
  end

  def phone_params
    params.require(:phone).permit(:number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_address.html.erb
<span class="address-data"><strong><%= t('address.address1') %></strong>: <%= address.address1 %></span>
<span class="address-data"><strong><%= t('address.address2') %></strong>: <%= address.try(:address2) %></span>
<span class="address-data"><strong><%= t('address.city') %></strong>: <%= address.city %></span>
<span class="address-data"><strong><%= t('address.state') %></strong>: <%= address.state %></span>
<span class="address-data"><strong><%= t('address.country') %></strong>: <%= address.country %></span>
<span class="address-data"><strong><%= t('address.zip_code') %></strong>: <%= address.zip_code %></span>

app/views/contacts/_form.html.erb
<%= form_for(@contact, html: { class: 'pure-form' }) do |form| %>
  <div class="pure-u-1">
    <fieldset class="pure-group">
      <%= form.text_field :name, placeholder: t('contact.name'), class: 'pure-input-1', required: true %>

      <%= form.text_field :last_name, placeholder: t('contact.last_name'), class: 'pure-input-1', required: true %>

      <%= form.text_area :bio, placeholder: t('contact.bio'), class: 'pure-input-1' %>
    </fieldset>

    <h3><%= t('contact.address') %></h3>
    <fieldset class="pure-group">
      <%= form.fields_for :address do |address_form| %>
        <%= address_form.text_field :address1, placeholder: t('address.address1'), class: 'pure-input-1', required: true %>

        <%= address_form.text_field :address2, placeholder: t('address.address2'), class: 'pure-input-1' %>

        <%= address_form.text_field :city, placeholder: t('address.city'), class: 'pure-input-1', required: true %>

        <%= address_form.text_field :state, placeholder: t('address.state'), class: 'pure-input-1', required: true %>

        <%= address_form.text_field :country, placeholder: t('address.country'), class: 'pure-input-1', required: true %>

        <%= address_form.text_field :zip_code, placeholder: t('address.zip_code'), class: 'pure-input-1', required: true %>
      <% end %>
    </fieldset>

    <div class="form-actions">
      <%= link_to t('contact.list'), contacts_path, class: 'pure-button' %>
      <%= form.submit t(:save), class: 'pure-button pure-button-primary' %>
    </div>
  </div>
<% end %>

app/views/contacts/index.html.erb
<div class="pure-g">
  <div class="pure-u-1">
    <div class="container">

      <%= search_form_for @q, class: 'pure-form' do |f| %>
        <%= f.text_field :name_or_last_name_cont, class: 'pure-input-1', placeholder: t(:search) %>
      <% end %>

      <h3><%= t('contact.list') %></h3>
      <%= link_to t('contact.new'), new_contact_path, class: 'pure-button large__btn pure-button-primary' %>

      <% @contacts.each do |contact| %>
        <%= link_to contact, contact_path(contact), class: 'pure-button large__btn' %>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="pure-g">
  <div class="pure-u-1">
    <div class="container">
      <h3><%= t('contact.new') %></h3>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="pure-g">
  <div class="pure-u-1">
    <div class="container">
      <h2><%= @contact %></h2>

      <div class="well">
        <%= form_for(@contact, html: { class: 'pure-form' }, method: :put) do |form| %>
          <fieldset>
            <%= text_field_tag 'contact[phones_attributes][0][number]', nil, placeholder: t('phone.number'), required: true %>
            <%= form.submit t('phone.create'), class: 'button-success pure-button' %>
          </fieldset>
        <% end %>
      </div>

      <div class="well">
        <h3 class="center"><%= t('contact.bio') %></h3>
        <p class="center"><%= @contact.try(:bio) %></p>
      </div>

      <div class="well">
        <h3 class="center"><%= t('contact.address') %></h3>
        <%= render @contact.address %>
      </div>

      <div class="well">
        <h3 class="center"><%= t('phone.numbers') %></h3>
        <%= render @contact.phones %>
      </div>

      <div class="form-actions">
        <%= link_to t('contact.list'), contacts_path, class: 'pure-button' %>
        <%= link_to t(:delete), contact_path(@contact), method: :delete, class: 'button-error pure-button' %>
        <%= link_to t(:edit), edit_contact_path(@contact), class: 'pure-button pure-button-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhoneDirectory</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/header' %>
<%= yield %>

</body>
</html>

app/views/phones/_form.html.erb
<%= form_for(@phone, html: { class: 'pure-form' }) do |form| %>
  <div class="pure-u-1">
    <fieldset class="pure-group">
      <%= form.text_field :number, placeholder: t('phone.number'), class: 'pure-input-1', required: true %>
    </fieldset>

    <div class="form-actions">
      <%= link_to t('contact.list'), contacts_path, class: 'pure-button' %>
      <%= form.submit t(:save), class: 'pure-button pure-button-primary' %>
    </div>
  </div>
<% end %>

app/views/phones/_phone.html.erb
<span><strong><%= t('phone.number') %></strong>: <%= phone.number %></span>
<%= link_to t(:edit), edit_phone_path(phone) %> |
<%= link_to t(:delete), phone_path(phone), method: :delete %><br/>

app/views/phones/edit.html.erb
<div class="pure-g">
  <div class="pure-u-1">
    <div class="container">
      <h3><%= t(:edit) %></h3>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="pure-menu pure-menu-horizontal">
  <%= link_to t(:app_title), contacts_path, class: 'pure-menu-heading pure-menu-link' %>
  <ul class="pure-menu-list right">
    <li class="pure-menu-item"><%= link_to t(:spanish), url_for(locale: 'es'), class: 'pure-menu-link' %></li>
    <li class="pure-menu-item"><%= link_to t(:english), url_for(locale: 'en'), class: 'pure-menu-link' %></li>
  </ul>
</div>